name: Combat
version: '${project.version}'
main: dk.yzhy.Combat
author: yzhy
description: Combat plugin with good performance.
commands:
  combat:
    description: A combat command!
    aliases: ct
  setcombat:
    permission: combat.set
